<suTransaction>:
#    name: "GUapplication"
    BoxLayout:
        BoxLayout
            orientation: "vertical"
            BoxLayout:
                size_hint_y: 0.1
                Label:
                    size_hint_x: 0.9
                GrayButton:
                    text:"Home"
                    size_hint_x: 0.1
                    size: 150, 100
                    on_press: root.tohome()